apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  type: LoadBalancer   # <--- เพิ่มบรรทัดนี้
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      # nodePort: 30081 # <--- เพิ่มบรรทัดนี้ (ใช้ port ที่ไม่ซ้ำกับ frontend)
  selector:
    io.kompose.service: backend
