apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Windows\system32\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - name: spring-backend
          image: bofwant5000bath-backend:latest   # ใช้ image local ที่คุณ build แล้ว
          imagePullPolicy: IfNotPresent           # ใช้ image local ก่อน ไม่พยายามดึงจาก Docker Hub
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: Id_6687001
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/devops_phase2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok&useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8mb4
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          ports:
            - containerPort: 8080